spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  datasource:
    url: jdbc:mysql://localhost:3307/payment_db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

razorpay:
  key_id: ${RAZORPAY_KEY_ID}
  key_secret: ${RAZORPAY_KEY_SECRET}
  webhook_secret: ${RAZORPAY_WEBHOOK_SECRET}
  mode: ${RAZORPAY_MODE:test}  # test/live 